src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="text")
     */
    private $contenu;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $photo;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="article", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="article")
     */
    private $user_id;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setArticle($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(?User $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }
}

src/Controller/BackOfficeController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Article;
use App\Entity\Comment;
use App\Entity\Category;
use App\Form\ArticleType;
use App\Form\CommentFormType;
use App\Form\CategoryFormType;
use App\Form\RegistrationFormType;
use PhpParser\Node\Expr\Isset_;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityRepository;
use App\Repository\ArticleRepository;
use App\Repository\CommentRepository;
use App\Repository\CategoryRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\Repository\RepositoryFactory;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

class BackOfficeController extends AbstractController
{
    // Méthode qui affiche la page Home du backoffice
    #[Route('/admin', name: 'app_admin')]
    public function adminHome(): Response
    {
        return $this->render('back_office/index.html.twig', [
            'controller_name' => 'BackOfficeController',
        ]);
    }

    #[Route('/admin/articles', name: 'app_admin_articles')]
    #[Route('/admin/article/{id}/remove', name: 'app_admin_article_remove')]
    public function adminArticles(EntityManagerInterface $manager, ArticleRepository $repoArticle, Article $artRemove=null): Response
    {
        // dd($artRemove);
        $colonnes = $manager->getClassMetadata(Article::class)->getFieldNames();
        // dd($colonnes);

        /*
            Exo: affiche sous forme de tableau HTML l'ensemble des articles stockés en BDD
            1.Sélectionner en BDD l'ensemble de la table 'article' et transmettre le résultat à la méthode render()
            2.dans le template 'admin_articles.html.twig, mettre en forme l'affichage des articles dans un tableau HTML
            3. Afficher le nom de la catégorie de chaque article
            4. Afficher le nombre de commentaire de chaque article
            5. Prévoir un lien modifier/supprimer pour chaque article
        */

        $articles = $repoArticle->findAll();
        // dd($articles);

        //Traitement suppression article en BDD

        if($artRemove)
        {
            $manager->remove($artRemove);
            $manager->flush();
            $titre = $artRemove->getTitre();
            $this->addFlash('success', "l'article $titre a bien été supprimé");
            return $this->redirectToRoute('app_admin_articles');
        }

        return $this->render('back_office/admin_articles.html.twig', [
            'colonnes'=>$colonnes,
            'articles' =>$articles
            
        ]);
    }

    #[Route('/admin/article/add', name:'app_admin_article_add')]
    #[Route('/admin/article/{id}/update', name:'app_admin_article_update')]
    public function admin_article_form(Article $article=null, Request $request, EntityManagerInterface $manager, SluggerInterface $slugger): Response
    {
        if(!$article)
        {
            $article = new Article;
        }

       if($article)
       {
           $photoActuelle = $article->getPhoto();
       }
        

        $formArticle = $this->createForm(ArticleType::class, $article);

        $formArticle->handleRequest($request);

        if($formArticle->isSubmitted() && $formArticle->isValid())
        {
            if(!$article->getId())
            {
                 $article->setDate(new \DateTime());
            }
           

            //Traitement de la photo
            
            $photo = $formArticle->get('photo')->getData();
            // dd($photo);

            
            if($photo)
            {
            
                $nomphoto = pathinfo($photo->getClientOriginalName(), PATHINFO_FILENAME);

                // dd($nomphoto);
                
                $securenomphoto = $slugger->slug($nomphoto);

                // dd($securenomphoto);

                $nouveaunomphoto = $securenomphoto.'-'. uniqid().'.'. $photo->guessExtension();

                // dd($nouveaunomphoto);

                try
                {
                    $photo->move(
                        $this->getParameter('photo_directory'),
                        $nouveaunomphoto
                    );

                }
                catch(FileException $e)
                {

                }

                $article->setPhoto($nouveaunomphoto);

            }

            else
            {
                //Si l'article possède une image mais qu'on ne souhaite pas la modifier, on renvoie la même image en BDD
                if(Isset($photoActuelle))
                {
                    $article->setPhoto($photoActuelle);
                }

                //Sinon on crée un nouvel article mais on ne souhaite pas uploader d'image, alors on renvoie NULL pour le champ photo dans la BDD
                else
                {
                    $article->setPhoto(null);
                }

            }
            if($article->getId())
            {
                $txt = 'modifié';
            }
            else
            {
                $txt = 'enregistré';
            }
            
            $manager->persist($article);
            $manager->flush();
            $this->addFlash('success', "Article $txt!");
            return $this->redirectToRoute('app_admin_articles');
        }
        
       
        return $this->render('back_office/admin_article_form.html.twig', [
            'formArticle'=>$formArticle->createView(),
            'photoActuelle'=> $article->getPhoto(),
            'editMode'=>$article->getId()
        ]);
    }

    #[Route('/admin/categories', name:'app_admin_categories')]
    #[Route('/admin/categories/{id}/delete', name:'app_admin_categories_delete')]
    public function adminCategories(CategoryRepository $repoCategory, EntityManagerInterface $manager, Category $catRemove=null):Response
    {
        $colonnes = $manager->getClassMetadata(Category::class)->getFieldNames();
        // dd($colonnes);
        $category = $repoCategory->findAll();
        
       
        if($catRemove)
        { 
            //On récupère le titre de la catégorie avant la suppression pour l'intégrer dans le message utilisateur
            $titre = $catRemove->getTitre();

            if($catRemove->getArticles()->isEmpty())
            {
                // dd($article);
                $manager->remove($catRemove);
                $manager->flush();
                $this->addFlash('success', "La catégorie $titre a bien été supprimée");
                return $this->redirectToRoute('app_admin_categories');

            }

            else
            {
                $this->addFlash('danger', "La catégorie $titre est encore liée à un ou plusieurs articles!");
                return $this->redirectToRoute('app_admin_categories');
            }

        }
        
        return $this->render('back_office/admin_categories.html.twig', [
            'category'=>$category,
            'colonnes'=>$colonnes
        ]);
    }
    
    #[Route('/admin/categories/add', name:'app_admin_categories_add')]
    #[Route('/admin/categories/{id}/update', name:'app_admin_categories_update')]
    public function addCategory(Request $request, EntityManagerInterface $manager, Category $category=null):Response
    {
        if(!$category)
        {
            $category = new Category;
        }
        

        $categoryForm = $this->createForm(CategoryFormType::class, $category);
        $categoryForm->handleRequest($request);

        if($categoryForm->isSubmitted() && $categoryForm->isValid())
        {
            $titre = $category->getTitre();
            
            if($category->getId())
            {
                $txt = "modifiée";
            }

            else
            {
                $txt = "ajoutée";
            }

            $manager->persist($category);
            $manager->flush();
            $this->addFlash('success', "Félicitations! la catégorie $titre a bien été $txt!");
            return $this->redirectToRoute('app_admin_categories');

        }
        return $this->render('back_office/admin_categorie_form.html.twig', [
            'categoryForm'=>$categoryForm->createView()
        ]);
    }

    #[Route('/admin/comments', name:'app_admin_comments')]
    #[Route('/admin/comments/{id}/delete', name:'app_admin_comments_delete')]
    public function adminComments(CommentRepository $repoComment, EntityManagerInterface $manager, Comment $commentRemove=null): Response
    {
        $commentaires = $repoComment->findAll();
        // dd($commentaires);
        $colonnes = $manager->getClassMetadata(Comment::class)->getFieldNames();
        // dd($colonnes);
        

        if($commentRemove)
        {
            //On stock l'auteur du commentaire dans une variable afin de l'intégrer dans le message de validation
            $auteur = $commentRemove->getAuteur();
            $manager->remove($commentRemove);
            $manager->flush();
            $this->addFlash('success', "le commentaire de $auteur à bien été supprimé");
            return $this->redirectToRoute('app_admin_comments');
        }


        return $this->render('back_office/admin_comments.html.twig', [
            'colonnes'=>$colonnes,
            'commentaires'=>$commentaires
        ]);
    }

    #[Route('/admin/comments/{id}/update', name:'app_admin_comments_update')]
    public function updateComment(Comment $comment, EntityManagerInterface $manager, Request $request): Response
    {
        
       
            $formComment = $this->createForm(CommentFormType::class, $comment, ['commentFormBack'=>true]);

            $formComment->handleRequest($request);

templates/back_office/admin_article_form.html.twig
{% extends "base_admin.html.twig" %}

{% block title %}
Blog Symfony | 
{% if editMode %}
    modification Article
    
    {% else %}
    Ajout article
{% endif %}

{% endblock %}

{% block body %}

<h1 class="text-center">
        {% if editMode %}
            Modifier un article
            {% else %}
            Ajouter un article
        {% endif %}   
</h1>

{{ form_start(formArticle)}}

    {{ form_row(formArticle.titre) }}
    {{ form_row(formArticle.contenu) }}
    {{ form_row(formArticle.category) }}
    {{ form_row(formArticle.photo) }}

    {% if photoActuelle != null %}
        <p><em>Votre photo actuelle</em>
        <img src="{{ asset('uploads/photos/' ~ photoActuelle)}}" alt="" class="col-4 img-responsive d-block">
        </p>
        
    {% endif %}

    <button>Enregistrer</button>

{{ form_end(formArticle)}}
    
{% endblock %}

templates/back_office/admin_articles.html.twig
{% extends "base_admin.html.twig" %}

{% block title %}
    Blog Symfony | Gestion des articles
{% endblock %}

{% block body %}

{{dump(articles)}}

    {% for message in app.flashes('success') %}

        <div class="bg-success col-5 text-center mx-auto my-4 p-3">{{message}}</div>
        
    {% endfor %}
    


    <table class="table table-striped text-center s" id="table-backoffice">
    <thead>
        <tr>
        {% for data in colonnes %}
        {# On exclue la colonne 'id' #}
        {% if data != 'id' %}
                {# capitalize : filtre Twig permettant de mettre la 1ère lettre de la chaine de caractères en majuscule #}
            <th class="border border-1 border-dark">{{data|capitalize}}</th>
            
        {% endif %}
            
        {% endfor %}
            <th class="border border-1 border-dark">CAT</th>
            <th class="border border-1 border-dark">Auteur</th>
            <th class="border border-1 border-dark">Nb Comm.</th>
            <th class="border border-1 border-dark">Action</th>
        </tr>
    </thead>
    <tbody>

        {% for data in articles %}
            <tr>
                <td>
                <a href="{{path('blog_show', {'id': data.id})}}">
                    {{ data.titre}}
                </a>
                </td>

                <td>{{ data.contenu|striptags|slice(0,100)}}[...]</td>

                {# Si la valeur de la photo en BDD est différente de null, cela veut dire qu'une photo a bien été téléchargée, on entre dans le IF et on affiche l'image #}
                {% if data.photo != null %}
                    <td><img src="{{ asset('uploads/photos/' ~ data.photo)}}" alt="{{data.titre}}"></td>
                    {% else %}
                    <td class="text-danger">Aucune photo uploadée</td>
                {% endif %}
                
                <td>{{ data.date|date('m/d/Y')}}</td>
                <td>{{ data.category.titre}}</td>
                <td>{{data.userId.prenom}} {{data.userId.nom}}</td>
                <td>{{ data.comments|length}}</td>
                <td>
                    <a href="#" onclick="return(confirm('Voulez-vous vraiment supprimmer l\'article n° {{data.id}}?'));"><span > <i class="bi bi-trash"></i></span></a>
                    <a href="{{path('app_admin_article_update', {'id': data.id})}}"><span><i class="bi bi-caret-up-square"></i></span></a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
    </tr></table>


    
{% endblock %}

templates/back_office/admin_categorie_form.html.twig
{% extends "base_admin.html.twig" %}

{% block title %}
    Blog Symfony | Ajout Catégorie
{% endblock %}

{% block body %}
<h1 class="text-center">Nouvelle catégorie</h1>

{{form_start(categoryForm, {'attr':{'class':'col-6 mx-auto'}}) }}

    {{form_row(categoryForm.titre)}}

    {{form_row(categoryForm.description)}}

    <button>Enregistrer</button>
{{form_end(categoryForm)}}


{% endblock %}

templates/back_office/admin_categories.html.twig
{% extends "base_admin.html.twig" %}

{% block title %}
    Blog Symfony | Catégories
{% endblock %}

{% block body %}
    <h1 class="text-center">Catégories</h1>

    {% for label, messages in app.flashes(['success', 'danger']) %}
        {% for message in messages %}

            <div class="bg-{{ label }} col-5 text-center mx-auto my-4 p-3 text-white">{{message}}</div>
        {% endfor %}
    {% endfor %}

    <table class="table table-bordered col-8 mx-auto">
        <tr>
            {% for data in colonnes %}
            
            <th class="text-center">{{data}}</th>
        
            {% endfor %}
            <th class="text-center">Nombre d'articles liés</th>
            <th class="text-center">Action</th>
       </tr>
        {% for data in category %}
           <tr> 
                <td class="text-center">{{ data.id }}</td>
                <td class="text-center">{{ data.titre }}</td>
                <td class="text-center">{{ data.description }}</td>
                <td class="text-center">{{data.articles|length}}</td> 
                <td class="text-center d-flex flex-column">
                    <a href="{{path('app_admin_categories_delete', {'id': data.id})}}" onclick="return(confirm('Voulez-vous réellement supprimer la catégorie {{ data.titre}}'));"><span > <i class="bi bi-trash"></i></span></a>
                    <a href="{{path('app_admin_categories_update', {'id': data.id})}}"><span><i class="bi bi-caret-up-square"></i></span></a>
                    <a href="{{path('app_admin_categories_add')}}" title="ajouter une catégorie"><i class="bi bi-plus-square-fill"></i></span></a>
                </td>
        </tr>
        {% endfor %}
      
    </table>    
{% endblock %}

templates/back_office/admin_comments.html.twig
{% extends "base_admin.html.twig" %}

{% block title %}
Blog BlogSymfony | Commentaires
    
{% endblock %}

{% block body %}
<h1 class="text-center">Liste des Commentaires</h1>

{% for message in app.flashes ('success') %}

    <div class="bg-success col-5 text-center mx-auto my-4 p-3 text-white">{{ message }}</div>

{% endfor %}

    <table class="table table-striped text-center s" id="table-comments">
    <thead>
        <tr >
            {% for data in colonnes %}

            {% if data != 'id' %}

                <th class="text-center p-2">{{data|capitalize}}</th>

            {% endif %}
            
            {% endfor %}
            <th>Action</th>
        </tr>
    </thead>

    <tbody>
        {% for data in commentaires %}
            <tr>
                
                <td class="text-center p-3">{{ data.commentaire|striptags}}</td>
                <td class="text-center p-3">{{ data.auteur}}</td>
                <td class="text-center p-3">{{ data.date|date('d/m/Y')}}</td>
                <td>
                    <a href="{{path('app_admin_comments_delete', {'id': data.id})}}" onclick="return(confirm('Voulez-vous vraiment supprimmer le commentaire de {{data.auteur}}?'));"><span > <i class="bi bi-trash"></i></span></a>
                    <a href="{{path('app_admin_comments_update', {'id': data.id })}}"><span><i class="bi bi-caret-up-square"></i></span></a>
                </td>
            </tr>
        {% endfor %}
    </tbody>

    </table>
{% endblock %}

templates/back_office/admin_comments_update.html.twig
{% extends "base_admin.html.twig" %}

{% block title %}
    Blog Symfony | Update comments
{% endblock %}

{% block body %}

<h1 class="text-center">Modifier le commentaire</h1>

{{ form_start(formComment, {'attr':{'class':'col-6 mx-auto'}}) }}
    {{ form_row(formComment.auteur) }}
    {{ form_row(formComment.commentaire) }}

    <button>Enregistrer</button>
{{ form_end(formComment) }}
    
{% endblock %}

templates/back_office/admin_users.html.twig
{% extends "base_admin.html.twig" %}
{% block title %}
    Blog Symfony | User List
{% endblock %}

{% block body %}

    {% for message in app.flashes('success') %}

        <div class="bg-success col-5 text-center mx-auto my-4 p-3">{{message}}</div>
        
    {% endfor %}

    <h1 class="text-center">Liste des Utilisateurs</h1>

   
    <table class="table table-striped text-center s" id="table-comments">
    <thead>
        <tr >
            {% for data in colonnes %}
            {% if data != 'password' %}
            
                <th class="text-center p-2">{{data|capitalize}}</th>
            {% endif %}
            
            {% endfor %}
            <th>Action</th>
        </tr>
    </thead>

    <tbody>
        {% for data in dataUser %}
            <tr>
                <td class="text-center p-3">{{ data.id}}</td>
                <td class="text-center p-3">{{ data.email}}</td>
                <td class="text-center p-3">
                {% for role in data.roles %}
                    
                    {% if role == 'ROLE_ADMIN'%}
                    Administrateur
                    {% elseif role == null %}
                    Utilisateur
                    {% endif %}
                   

                {% endfor %}
                </td>
                <td class="text-center p-3">{{ data.prenom}}</td>
                <td class="text-center p-3">{{ data.nom}}</td>
                <td class="text-center p-3">{{ data.adresse}}</td>
                <td class="text-center p-3">{{ data.ville}}</td>
                <td class="text-center p-3">{{ data.codePostal}}</td>


                <td>
                    <a href="{{path('app_admin_users_delete', {'id': data.id})}}" onclick="return(confirm('Voulez-vous vraiment supprimmer {{data.prenom}} {{data.nom}}?'));"><span > <i class="bi bi-trash"></i></span></a>
                    <a href="{{path('app_admin_users_update', {'id': data.id})}}"><span><i class="bi bi-caret-up-square"></i></span></a>
                    <a href="{{path('app_admin_users_add')}}" title="ajouter un utilisateur "><i class="bi bi-plus-square-fill"></i></span></a>
                </td>
            </tr>
        {% endfor %}
    </tbody>

    </table>

    {# {% if app.request.query.get('action') == 'update' %}
        affichage formulaire

        {{form_start(userForm)}}
        
            {{form_row(userForm.roles)}}

        {{form_end(userForm)}}
    {% endif %} 
    ?action=update (mettre dans l'url)
    #}
{% endblock %}

templates/back_office/admin_users_form.html.twig
{% extends "base_admin.html.twig" %}

{% block title %}
    Blog Symfony| Nouvel utilisateur 
{% endblock %}

{% block body %}
    
    {{form_start(userForm)}}

        {{ form_row(userForm.email) }}

        {{ form_row(userForm.prenom) }}

        {{ form_row(userForm.nom) }}

        {{ form_row(userForm.adresse) }}

        {{ form_row(userForm.ville) }}

        {{ form_row(userForm.codePostal) }}

        {{ form_row(userForm.password)}}

        <button type="submit" class="btn btn-dark">Valider</button>
    {{form_end(userForm)}}

{% endblock %}

templates/back_office/admin_users_update.html.twig
{% extends "base_admin.html.twig" %}
{% block title %}
    Blog Symfony|Update
{% endblock %}

{% block body %}
<h1>Profil de {{name}}</h1>

    {{form_start(userForm)}}

        {{form_row(userForm.roles)}}

        <button>Modifier</button>
    {{form_end(userForm)}}


{% endblock %}

templates/back_office/index.html.twig
{% extends 'base_admin.html.twig' %}

{% block title %}Blog Symfony | Backoffice{% endblock %}

{% block body %}

    <h1 class="text-center my-5">Bienvenue dans votre Backoffice, {{app.user.prenom}} {{app.user.nom}}!</h1>

    <h4 class="text-center mb-5">vous êtes dans votre espace BackOffice</h4>

    <p class="text-center">Vous pouvez ici gérer la totalité de votre Blog: les articles, catégories, commentaires et utilisateurs.</p>
{% endblock %}